version: "3.9"
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_ACCESS_KEY=wD850kCkp6eU6hlk7vIV
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
    restart: unless-stopped
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add kopalol http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb kopalol/uploads;
      /usr/bin/mc policy set public kopalol/uploads;
      exit 0;
      "
networks:
  minionetwork:
    driver: bridge
volumes:
  minio_data:
    driver: local
