// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: files.sql

package queries

import (
	"context"
)

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFileForDeletion = `-- name: GetFileForDeletion :one
SELECT id, file_extension, file_type, file_name, original_file_name, file_size, md5_hash, deletion_key, created_at FROM files WHERE id = ? AND deletion_key = ? LIMIT 1
`

type GetFileForDeletionParams struct {
	ID          string
	DeletionKey string
}

func (q *Queries) GetFileForDeletion(ctx context.Context, arg GetFileForDeletionParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileForDeletion, arg.ID, arg.DeletionKey)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileExtension,
		&i.FileType,
		&i.FileName,
		&i.OriginalFileName,
		&i.FileSize,
		&i.Md5Hash,
		&i.DeletionKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (
    id, 
    file_extension, 
    file_type, 
    file_name, 
    original_file_name, 
    file_size,
    md5_hash,
    deletion_key
) VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, file_extension, file_type, file_name, original_file_name, file_size, md5_hash, deletion_key, created_at
`

type InsertFileParams struct {
	ID               string
	FileExtension    string
	FileType         string
	FileName         string
	OriginalFileName string
	FileSize         int64
	Md5Hash          string
	DeletionKey      string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, insertFile,
		arg.ID,
		arg.FileExtension,
		arg.FileType,
		arg.FileName,
		arg.OriginalFileName,
		arg.FileSize,
		arg.Md5Hash,
		arg.DeletionKey,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileExtension,
		&i.FileType,
		&i.FileName,
		&i.OriginalFileName,
		&i.FileSize,
		&i.Md5Hash,
		&i.DeletionKey,
		&i.CreatedAt,
	)
	return i, err
}
