// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: uploads.sql

package queries

import (
	"context"
)

const insertFile = `-- name: InsertFile :one
INSERT INTO files (
    id, 
    file_extension, 
    file_type, 
    file_name, 
    original_file_name, 
    file_size, 
    deletion_key
) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, file_extension, file_type, file_name, original_file_name, file_size, deletion_key, created_at
`

type InsertFileParams struct {
	ID               string
	FileExtension    string
	FileType         string
	FileName         string
	OriginalFileName string
	FileSize         int64
	DeletionKey      string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, insertFile,
		arg.ID,
		arg.FileExtension,
		arg.FileType,
		arg.FileName,
		arg.OriginalFileName,
		arg.FileSize,
		arg.DeletionKey,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileExtension,
		&i.FileType,
		&i.FileName,
		&i.OriginalFileName,
		&i.FileSize,
		&i.DeletionKey,
		&i.CreatedAt,
	)
	return i, err
}
